from namedlist import namedlist

#scale_factor = 20.0/float(options.nuclei_size)
Config = namedlist("Config", [
    "phase",
    "dataset_path",
    "input_channel_files",
    "target_channel_files",
    "iter_size",
    "folder",
    "target_rows",
    "target_cols",
    "input_channel_num",
    "network",
    "loss",
    "optimizer",
    "lr",
    "lr_steps",
    "lr_gamma",
    "batch_size",
    "epoch_size",
    "nb_epoch",
    "predict_batch_size",
    "test_pad",
    "weights_dir",
    "logs_dir",
    "outputs_dir",
    "target_channel_num",
    "ignore_target_size",
    "warmup",
    "activation",
    "scale_factor",
    "load_model_from",
    "num_workers",
    "device",
    "save_interval",
    "training_augmentations",
    "inputs_preprocessing",
    "targets_preprocessing"
])

def get_default_config():
    cfg = {
      "phase": "train",
      "batch_size": 16,
      "iter_size": 1,
      "dataset_path": "/imjoy/imjoy-paper/data-science-bowl/dsb2018-dataset-v0.1.1",
      "input_channel_files": ["nuclei.png"],
      "target_channel_files": "nuclei_border_mask.png",
      "folder": "dpn_unet_f0",
      "lr": 5e-5,
      "lr_steps": [[8, 1e-5], [12, 5e-6], [15, 1e-6]],
      "lr_gamma": 0.9,
      "nb_epoch": 20,
      "input_channel_num": 3,
      "test_pad": 0,
      "epoch_size": 24,
      "predict_batch_size": 1,
      "weights_dir": "../weights",
      "logs_dir": "../logs",
      "outputs_dir": "../outputs",
      "target_cols": 512,
      "target_rows": 512,
      "network": "dpn",
      "loss": {"type": "bce", "ce": 0.6, "dice_body": 0.2, "dice_border": 0.2},
      "optimizer": "adam",
      "target_channel_num": 3,
      "ignore_target_size": True,
      "warmup": 0,
      "activation": 'softmax',
      "scale_factor": 1.0,
      "load_model_from": None,
      "num_workers": 1,
      "device": 'cpu',
      "save_interval": 10,
      "training_augmentations": 'victor',
      "inputs_preprocessing": 'min-max',
      "targets_preprocessing": 'bit-depth'
    }
    return Config(**cfg)